version: 1.0.{build}
branches:
  only:
  - appveyor
clone_depth: 1
environment:
  nodejs_version: 8
install:
- ps: Install-Product node $env:nodejs_version
- yarn install
cache: '%LOCALAPPDATA%\Yarn'
build_script:
- cmd: >-
    yarn run ci
artifacts:
- path: dist\Vortex Setup *.exe
  name: Setup
